### ISSUE TITLE
`MonadIO` for all read*, get* and put*?

### ISSUE THREAD

**Issue by howsiwei** [snoyberg/basic-prelude#75]
Currently the functions do not have consistent types. Some work with `IO` while others work with any `MonadIO`. eg. `putStr :: MonadIO m => Text -> m ()` but `putChar :: Char -> IO ()`.

**Comment by snoyberg** [comment]
I think they should all be generalized. Note that this would surprisingly be a breaking change, since someone who imported the identifiers from both this module and the source module they are reexported from would now get a name collision. I still think it's worth it. Yet again: are you up for sending a PR?

Thanks for noticing all of these issues 👍
